 tw: {
    app_name: "心中之火",
    login: "登入",
    chapter: "章",
    chapters: "章節",
    audioBook: "有聲書",
    register_now: "立即註冊",
    discover: "發現",
    name: "姓名",
    enter_name: "輸入姓名",
    email: "電子郵件",
    enter_email: "輸入電子郵件",
    password: "密碼",
    enter_password: "輸入密碼",
    register: "註冊",
    forgot_password: "忘記密碼",
    already_account: "已經有帳號了嗎？",
    click_here_to_login: "點此登入",
    forgot_password_title: "忘記密碼",
    verify: "核實",
    back_to_register: "返回註冊頁面",
    please_login: "請輸入您的登入資訊",
    dont_have_account: "還沒有帳號？",
    Click_here_to_register: "點此註冊",
    privacy_policy: "隱私權政策",
    terms_service: "服務條款",
    accessibility: "無障礙聲明",
    cookie_policy: "Cookie 政策",
    rights_reserved: "© 2025 Indel Service, LLC. 版權所有。", start from here 
    listen: "聆聽",
    read: "讀",
    podcast: "podcast",
    profile: "輪廓",
    back_to_dashboard: "返回主控台",
    listen_upper: "聆聽",
    read_upper: "閱讀",
    podcast_upper: "播客",
    select_language: "選擇語言",
    my_account: "我的帳戶",
    logout: "登出",
    logging_in: "登入中…",
    fire_within: "心中之火",
    back_to_website: "返回網站",
    registering: "註冊中…",
    please: "請輸入",
    enter_your: "您的",
    details_to: "詳細資料",
    verifying: "驗證中…",
    contents: "目錄",
    loading: "載入中…",
    updating: "更新中…",
    update: "更新",
    old_password: "舊密碼",
    enter_old_password: "輸入舊密碼",
    new_password: "新密碼",
    verify_password: "確認新密碼",
    welcome: "歡迎",
    change_password: "變更密碼",
    thank_you_for_registering: "感謝您的註冊！",
    email_for_login_credentials: "登入憑證的電子郵件",
    back_to: "返回",
    set_your_new_password: "設定您的新密碼",
    password_must_include_a_special_character:
      "密碼必須包含特殊字符 (!@#$%^&*)",
    password_must_include_a_number: "密碼必須包含數字",
    password_must_include_an_uppercase_letter: "密碼必須包含大寫字母",
    Password_character: "密碼至少需要 8 個字元",
    new_password_is_required: "需要新密碼",
 
    // Description content
    title: "內心之火",
    description: `《心中之火》是實業家亨利·M·羅恩（Henry M. Rowan）的自傳，記載了他從一名年輕工程師，
  成長為應達工業集團（Inductotherm Industries, Inc.）創辦人的非凡歷程。
  本書回顧了他從小鎮生活、經歷二戰飛行學校，直至投身創業的人生軌跡。
  1953 年，羅恩在自家的廚房餐桌上創立了 Inductotherm，
  他賣掉房子、孤注一擲追求自己的願景。
  1992 年，他向紐澤西州一所小型學院捐贈了一億美元，創下紀錄並引發國際關注，
  但這只是他一生中眾多大膽抉擇與堅韌精神的一個篇章。
  《心中之火》不僅是一個關於創新與毅力的故事，
  更是一個典型的美國成功傳奇。`,
  },